# Discrete Distributions

**Chapter Preview**.

This table of distributions is a summary of selected discrete probability distributions used throughout *Loss Data Analytics*.

##(a,b,0) Class Distributions

```{r eval=TRUE, include=FALSE}
require(actuar)
```

</center>

<div class="tab">
  <button class="tablinks" onclick="openTab(event, 'disA')">Poisson</button>
  <button class="tablinks" onclick="openTab(event, 'disB')">Geometric</button>
  <button class="tablinks" onclick="openTab(event, 'disC')">Binomial</button>
  <button class="tablinks" onclick="openTab(event, 'disD')">Negative Binomial</button>
</div>

<div id="disA" class="tabcontent">
  <span onclick="this.parentElement.style.display='none'" class="topright">Hide</span>
  <h3>Poisson</h3>
  <p>

Poisson Functions

$$
{\small
\begin{matrix}
\begin{array}{l|c}
\hline
  \text{Name} & \text{Function} \\
\hline
  p_0 & e^{-\lambda} \\
\hline
  \text{Probability Mass Function} & \frac{e^{-\lambda}\lambda^k}{k!} \\
  p_k & \\
\hline
  \text{Expected Value} & \lambda \\
  \mathrm{E[N]} & \\
\hline
  \text{Variance} & \lambda \\
\hline
  \text{Probability Generating Function} & e^{\lambda(z-1)} \\
  \mathrm{P(z)} & \\
  \hline
  \text{a and b for recursion} & a=0 \\
   & b=\lambda \\
\hline
\end{array}
\end{matrix}
}
$$

Poisson R Commands

$$
{\small
\begin{matrix}
\begin{array}{l|c}
\hline
  \text{Density Function} & \text{dpois}(x=, lambda=\lambda) \\
\hline
  \text{Distribution Function} & \text{ppois}(p=, lambda=\lambda) \\
\hline
  \text{Quantile Function} & \text{qpois}(q=, lambda=\lambda) \\ 
\hline
  \text{Random Sampling Function} & \text{rpois}(n=, lambda=\lambda) \\
\hline
\end{array}
\end{matrix}
}
$$

</p>
</div>

<div id="disB" class="tabcontent">
  <span onclick="this.parentElement.style.display='none'" class="topright">Hide</span>
  <h3>Geometric</h3>
  <p>

Geometric Functions

$$
{\small
\begin{matrix}
\begin{array}{l|c}
\hline
  \text{Name} & \text{Function} \\
\hline
  p_0 & \frac{1}{1+\beta} \\
\hline
  \text{Probability Mass Function} & \frac{\beta^k}{(1+\beta)^{k+1}} \\
  p_k & \\
\hline
  \text{Expected Value} & \beta \\
  \mathrm{E[N]} & \\
\hline
  \text{Variance} & \beta(1+\beta) \\
\hline
  \text{Probability Generating Function} & [1-\beta(z-1)]^{-1} \\
  \mathrm{P(z)} & \\
  \hline
  \text{a and b for recursion} & a=\frac{\beta}{1+\beta} \\
   & b=0 \\
\hline
\end{array}
\end{matrix}
}
$$

Geometric R Commands

$$
{\small
\begin{matrix}
\begin{array}{l|c}
\hline
  \text{Density Function} & \text{dgeom}(x=, prob=\frac{1}{1+\beta}) \\
\hline
  \text{Distribution Function} & \text{pgeom}(p=, prob=\frac{1}{1+\beta}) \\
\hline
  \text{Quantile Function} & \text{qgeom}(q=, prob=\frac{1}{1+\beta}) \\ 
\hline
  \text{Random Sampling Function} & \text{rgeom}(n=, prob=\frac{1}{1+\beta}) \\
\hline
\end{array}
\end{matrix}
}
$$

</p>
</div>

<div id="disC" class="tabcontent">
  <span onclick="this.parentElement.style.display='none'" class="topright">Hide</span>
  <h3>Binomial</h3>
  <p>

Binomial Functions

$$
{\small
\begin{matrix}
\begin{array}{l|c}
\hline
  \text{Name} & \text{Function} \\
\hline
  \text{Parameter Assumptions} & 0<q<1,~\text{m is an integer} \\
   & 0 \leq k \leq m\\
\hline
  p_0 &(1-q)^m \\
\hline
  \text{Probability Mass Function} & \binom{m}{k}q^k(1-q)^{m-k} \\
  p_k & \\
\hline
  \text{Expected Value} & mq \\
  \mathrm{E[N]} & \\
\hline
  \text{Variance} & mq(1-q) \\
\hline
  \text{Probability Generating Function} & [1+q(z-1)]^m \\
  \mathrm{P(z)} & \\
  \hline
  \text{a and b for recursion} & a=\frac{-q}{1-q} \\
   & b=\frac{(m+1)q}{1-q} \\
\hline
\end{array}
\end{matrix}
}
$$

Binomial R Commands

$$
{\small
\begin{matrix}
\begin{array}{l|c}
\hline
  \text{Density Function} & \text{dbinom}(x=, size=m, prob=p) \\
\hline
  \text{Distribution Function} & \text{pbinom}(p=, size=m, prob=p) \\
\hline
  \text{Quantile Function} & \text{qbinom}(q=, size=m, prob=p) \\ 
\hline
  \text{Random Sampling Function} & \text{rbinom}(n=, size=m, prob=p) \\
\hline
\end{array}
\end{matrix}
}
$$

</p>
</div>

<div id="disD" class="tabcontent">
  <span onclick="this.parentElement.style.display='none'" class="topright">Hide</span>
  <h3>Negative Binomial</h3>
  <p>

Negative Binomial Functions

$$
{\small
\begin{matrix}
\begin{array}{l|c}
\hline
  \text{Name} & \text{Function} \\
\hline
  p_0 & (1+\beta)^{-r} \\
\hline
  \text{Probability Mass Function} & \frac{r(r+1)\cdots(r+k-1)\beta^k}{k!(1+\beta)^{r+k}} \\
  p_k & \\
\hline
  \text{Expected Value} & r\beta \\
  \mathrm{E[N]} & \\
\hline
  \text{Variance} & r\beta(1+\beta) \\
\hline
  \text{Probability Generating Function} & [1-\beta(z-1)]^{-r} \\
  \mathrm{P(z)} & \\
  \hline
  \text{a and b for recursion} & a=\frac{\beta}{1+\beta} \\
   & b=\frac{(r-1)\beta}{1+\beta} \\
\hline
\end{array}
\end{matrix}
}
$$

Negative Binomial R Commands

$$
{\small
\begin{matrix}
\begin{array}{l|c}
\hline
  \text{Density Function} & \text{dnbinom}(x=, size=r, prob=\frac{1}{1+\beta}) \\
\hline
  \text{Distribution Function} & \text{pnbinom}(p=, size=r, prob=\frac{1}{1+\beta}) \\
\hline
  \text{Quantile Function} & \text{qnbinom}(q=, size=r, prob=\frac{1}{1+\beta}) \\ 
\hline
  \text{Random Sampling Function} & \text{rnbinom}(n=, size=r, prob=\frac{1}{1+\beta}) \\
\hline
\end{array}
\end{matrix}
}
$$

</p>
</div>

## (a,b,1) Class Distributions - Zero Truncated

</center>

<div class="tab">
  <button class="tablinks" onclick="openTab(event, 'ztA')">Zero Truncated Poisson</button>
  <button class="tablinks" onclick="openTab(event, 'ztB')">Zero Truncated Geometric</button>
  <button class="tablinks" onclick="openTab(event, 'ztC')">Zero Truncated Binomial</button>
  <button class="tablinks" onclick="openTab(event, 'ztD')">Zero Truncated Negative Binomial</button>
  <button class="tablinks" onclick="openTab(event, 'ztE')">Logarithmic</button>
</div>

<div id="ztA" class="tabcontent">
  <span onclick="this.parentElement.style.display='none'" class="topright">Hide</span>
  <h3>Zero Truncated Poisson</h3>
  <p>

Zero Truncated Poisson Functions

$$
{\small
\begin{matrix}
\begin{array}{l|c}
\hline
  \text{Name} & \text{Function} \\
\hline
  p^T_1 & \frac{\lambda}{e^\lambda-1} \\
\hline
  \text{Probability Mass Function} & \frac{\lambda^k}{k!(e^\lambda-1)} \\
  p^T_k & \\
\hline
  \text{Expected Value} & \frac{\lambda}{1-e^{-\lambda}} \\
  \mathrm{E[N]} & \\
\hline
  \text{Variance} & \frac{\lambda[1-(\lambda+1)e^{-\lambda}]}{(1-e^{-\lambda})^2} \\
\hline
  \tilde\lambda & ln(\frac{n\hat\mu}{n_1}) \\
\hline
  \text{Probability Generating Function} & \frac{e^{\lambda z}-1}{e^\lambda-1} \\
  \mathrm{P(z)} & \\
\hline
  \text{a and b for recursion} & a=0 \\
   & b=\lambda \\
\hline
\end{array}
\end{matrix}
}
$$

Zero Truncated Poisson R Commands

$$
{\small
\begin{matrix}
\begin{array}{l|c}
\hline
  \text{Density Function} & \text{dztpois}(x=, lambda=\lambda) \\
\hline
  \text{Distribution Function} & \text{pztpois}(p=, lambda=\lambda) \\
\hline
  \text{Quantile Function} & \text{qztpois}(q=, lambda=\lambda) \\ 
\hline
  \text{Random Sampling Function} & \text{rztpois}(n=, lambda=\lambda) \\
\hline
\end{array}
\end{matrix}
}
$$

</p>
</div>

<div id="ztB" class="tabcontent">
  <span onclick="this.parentElement.style.display='none'" class="topright">Hide</span>
  <h3>Zero Truncated Geometric</h3>
  <p>

Zero Truncated Geometric Functions

$$
{\small
\begin{matrix}
\begin{array}{l|c}
\hline
  \text{Name} & \text{Function} \\
\hline
  p^T_1 & \frac{1}{1+\beta} \\
\hline
  \text{Probability Mass Function} & \frac{\beta^{k-1}}{(1+\beta)^k} \\
  p^T_k & \\
\hline
  \text{Expected Value} & 1+\beta \\
  \mathrm{E[N]} & \\
\hline
  \text{Variance} & \beta(1+\beta) \\
\hline
  \tilde\beta & \hat\mu-1 \\
\hline
  \text{Probability Generating Function} & \frac{[1-\beta(z-1)]^{-1}-(1+\beta)^{-1}}{1-(1+\beta)^{-1}} \\
  \mathrm{P(z)} & \\
\hline
  \text{a and b for recursion} & a=\frac{\beta}{1+\beta} \\
   & b=0 \\
\hline
\end{array}
\end{matrix}
}
$$

Zero Truncated Geometric R Commands

$$
{\small
\begin{matrix}
\begin{array}{l|c}
\hline
  \text{Density Function} & \text{dztgeom}(x=, prob=\frac{1}{1+\beta}) \\
\hline
  \text{Distribution Function} & \text{pztgeom}(p=, prob=\frac{1}{1+\beta}) \\
\hline
  \text{Quantile Function} & \text{qztgeom}(q=, prob=\frac{1}{1+\beta}) \\ 
\hline
  \text{Random Sampling Function} & \text{rztgeom}(n=, prob=\frac{1}{1+\beta}) \\
\hline
\end{array}
\end{matrix}
}
$$

</p>
</div>

<div id="ztC" class="tabcontent">
  <span onclick="this.parentElement.style.display='none'" class="topright">Hide</span>
  <h3>Zero Truncated Binomial</h3>
  <p>

Zero Truncated Binomial Functions

$$
{\small
\begin{matrix}
\begin{array}{l|c}
\hline
  \text{Name} & \text{Function} \\
\hline
  \text{Parameter Assumptions} & 0<q<1,~\text{m is an integer} \\
   & 0 \leq k \leq m\\
\hline
  p^T_1 & \frac{m(1-q)^{m-1}q}{1-(1-q)^m} \\
\hline
  \text{Probability Mass Function} & \frac{\binom{m}{k}q^k(1-q)^{m-k}}{1-(1-q)^m} \\
  p^T_k & \\
\hline
  \text{Expected Value} & \frac{mq}{1-(1-q)^m} \\
  \mathrm{E[N]} & \\
\hline
  \text{Variance} & \frac{mq[(1-q)-(1-q+mq)(1-q)^m]}{[1-(1-q)^m]^2} \\
\hline
  \tilde q & \frac{\hat\mu}{m} \\
\hline
  \text{Probability Generating Function} & \frac{[1+q(z-1)^m]-(1-q)^m}{1-(1-q)^m} \\
  \mathrm{P(z)} & \\
\hline
  \text{a and b for recursion} & a=\frac{1}{1-q} \\
   & b=\frac{(m+1)q}{1-q} \\
\hline
\end{array}
\end{matrix}
}
$$

Zero Truncated Binomial R Commmands

$$
{\small
\begin{matrix}
\begin{array}{l|c}
\hline
  \text{Density Function} & \text{dztbinom}(x=, size=m, prob=p) \\
\hline
  \text{Distribution Function} & \text{pztbinom}(p=, size=m, prob=p) \\
\hline
  \text{Quantile Function} & \text{qztbinom}(q=, size=m, prob=p) \\ 
\hline
  \text{Random Sampling Function} & \text{rztbinom}(n=, size=m, prob=p) \\
\hline
\end{array}
\end{matrix}
}
$$

</p>
</div>

<div id="ztD" class="tabcontent">
  <span onclick="this.parentElement.style.display='none'" class="topright">Hide</span>
  <h3>Zero Truncated Negative Binomial</h3>
  <p>

Zero Truncated Negative Binomial Functions

$$
{\small
\begin{matrix}
\begin{array}{l|c}
\hline
  \text{Name} & \text{Function} \\
\hline
  \text{Parameter Assumptions} & r>-1, r\neq0 \\
\hline
  p^T_1 & \frac{r\beta}{(1+\beta)^{r+1}-(1+\beta)} \\
\hline
  \text{Probability Mass Function} & \frac{r(r+1)\cdots(r+k-1)}{k![(1+\beta)^r-1]}(\frac{\beta}{1+\beta})^k \\
  p^T_k & \\
\hline
  \text{Expected Value} & \frac{r\beta}{1-(1+\beta)^{-r}} \\
  \mathrm{E[N]} & \\
\hline
  \text{Variance} & \frac{r\beta[(1+\beta)-(1+\beta+r\beta)(1+\beta)^{-r}]}{[1-(1+\beta)^{-r}]^2} \\
\hline
  \tilde\beta & \frac{\hat\sigma^2}{\hat\mu}-1 \\
\hline
  \tilde r & \frac{\hat\mu^2}{\hat\sigma^2-\hat\mu} \\
\hline
  \text{Probability Generating Function} & \frac{[1-\beta(z-1)]^{-r}-(1+\beta)^{-r}}{1-(1+\beta)^{-r}} \\
  \mathrm{P(z)} & \\
\hline
  \text{a and b for recursion} & a=\frac{\beta}{1+\beta} \\
   & b=\frac{(r-1)\beta}{1+\beta} \\
\hline
\end{array}
\end{matrix}
}
$$

Zero Truncated Negative Binomial R Commands

$$
{\small
\begin{matrix}
\begin{array}{l|c}
\hline
  \text{Density Function} & \text{dztnbinom}(x=, size=r, prob=\frac{1}{1+\beta}) \\
\hline
  \text{Distribution Function} & \text{pztnbinom}(p=, size=r, prob=\frac{1}{1+\beta}) \\
\hline
  \text{Quantile Function} & \text{qztnbinom}(q=, size=r, prob=\frac{1}{1+\beta}) \\ 
\hline
  \text{Random Sampling Function} & \text{rztnbinom}(n=, size=r, prob=\frac{1}{1+\beta}) \\
\hline
\end{array}
\end{matrix}
}
$$

</p>
</div>

<div id="ztE" class="tabcontent">
  <span onclick="this.parentElement.style.display='none'" class="topright">Hide</span>
  <h3>Logarithmic</h3>
  <p>

Logarithmic Functions

$$
{\small
\begin{matrix}
\begin{array}{l|c}
\hline
  \text{Name} & \text{Function} \\
\hline
  p^T_1 & \frac{\beta}{(1+\beta)ln(1+\beta)} \\
\hline
  \text{Probability Mass Function} & \frac{\beta^k}{k(1+\beta)^k ln(1+\beta)} \\
  p^T_k & \\
\hline
  \text{Expected Value} & \frac{\beta}{ln(1+\beta)} \\
  \mathrm{E[N]} & \\
\hline
  \text{Variance} & \frac{\beta[1+\beta-\frac{\beta}{ln(1+\beta)}]}{ln(1+\beta)} \\
\hline
  \tilde\beta & \frac{n\hat\mu}{n_1}-1~=~ \frac{2(\hat\mu-1)}{\hat\mu} \\
\hline
  \text{Probability Generating Function} & 1-\frac{ln[1-\beta(z-1)]}{ln(1+\beta)} \\
  \mathrm{P(z)} & \\
\hline
  \text{a and b for recursion} & a=\frac{\beta}{1+\beta} \\
   & b=\frac{-\beta}{1+\beta} \\
\hline
\end{array}
\end{matrix}
}
$$

Logarithmic R Commands

$$
{\small
\begin{matrix}
\begin{array}{l|c}
\hline
  \text{Density Function} & \text{dnbinom}(x=,prob=\frac{\beta}{1+\beta}) \\
\hline
  \text{Distribution Function} & \text{pnbinom}(p=,prob=\frac{\beta}{1+\beta}) \\
\hline
  \text{Quantile Function} & \text{qnbinom}(q=,prob=\frac{\beta}{1+\beta}) \\ 
\hline
  \text{Random Sampling Function} & \text{rnbinom}(n=,prob=\frac{\beta}{1+\beta}) \\
\hline
\end{array}
\end{matrix}
}
$$

</p>
</div>